import { jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { users } from "./users";

export const auditLogs = pgTable("audit_log", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("user_id").references(() => users.id, { onDelete: "set null" }),
  action: text("action").notNull(),
  resource: text("resource"),
  resourceId: text("resource_id"),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
});

export type AuditLog = typeof auditLogs.$inferSelect;
export type NewAuditLog = typeof auditLogs.$inferInsert;

export const AUDIT_ACTIONS = {
  LOGIN: "auth:login",
  LOGOUT: "auth:logout",
  LOGIN_FAILED: "auth:login_failed",
  REGISTER: "auth:register",
  VERIFY_EMAIL: "auth:verify_email",
  FORGOT_PASSWORD: "auth:forgot_password",
  RESET_PASSWORD: "auth:reset_password",
  CHANGE_PASSWORD: "auth:change_password",
  UPDATE_PROFILE: "user:update_profile",
  UPDATE_AVATAR: "user:update_avatar",
  REMOVE_AVATAR: "user:remove_avatar",
  UPDATE_COVER: "user:update_cover",
  REMOVE_COVER: "user:remove_cover",
  UPDATE_SETTINGS: "user:update_settings",
  ROLE_CHANGE: "admin:role_change",
  USER_BAN: "admin:user_ban",
  USER_UNBAN: "admin:user_unban",
  FORUM_CATEGORY_CREATE: "forum:category:create",
  FORUM_CATEGORY_UPDATE: "forum:category:update",
  FORUM_CATEGORY_DELETE: "forum:category:delete",
  FORUM_CREATE: "forum:create",
  FORUM_UPDATE: "forum:update",
  FORUM_DELETE: "forum:delete",
  THREAD_CREATE: "thread:create",
  THREAD_UPDATE: "thread:update",
  THREAD_DELETE: "thread:delete",
  THREAD_PIN: "thread:pin",
  THREAD_UNPIN: "thread:unpin",
  THREAD_LOCK: "thread:lock",
  THREAD_UNLOCK: "thread:unlock",
  THREAD_FEATURE: "thread:feature",
  THREAD_UNFEATURE: "thread:unfeature",
  THREAD_WATCH: "thread:watch",
  THREAD_UNWATCH: "thread:unwatch",
  THREAD_BOOKMARK: "thread:bookmark",
  THREAD_UNBOOKMARK: "thread:unbookmark",
  POST_CREATE: "post:create",
  POST_UPDATE: "post:update",
  POST_DELETE: "post:delete",
  POST_RESTORE: "post:restore",
  POST_HIDE: "post:hide",
  POST_UNHIDE: "post:unhide",
  POST_REPORT_CREATE: "post_report:create",
  POST_REPORT_RESOLVE: "post_report:resolve",
  POST_REPORT_REJECT: "post_report:reject",
  ATTACHMENT_UPLOAD: "attachment:upload",
  ATTACHMENT_DELETE: "attachment:delete",
  ATTACHMENT_DELETE_OWN: "attachment:delete_own",
  MEDIA_UPLOAD: "media:upload",
  MEDIA_DELETE: "media:delete",
  EDITOR_DRAFT_SAVE: "editor_draft:save",
  EDITOR_DRAFT_RECOVER: "editor_draft:recover",
  REACTION_CREATED: "reaction:created",
  REACTION_REMOVED: "reaction:removed",
  REPUTATION_CHANGED: "reputation:changed",
  BADGE_EARNED: "badge:earned",
  BADGE_REVOKED: "badge:revoked",
  TROPHY_UNLOCKED: "trophy:unlocked",
  TROPHY_REVOKED: "trophy:revoked",
  LEVEL_UP: "level:up",
  ADMIN_REPUTATION_AWARD: "admin:reputation:award",
  ADMIN_BADGE_ASSIGN: "admin:badge:assign",
  ADMIN_TROPHY_ASSIGN: "admin:trophy:assign",
  ORDER_CREATED: "order:created",
  ORDER_UPDATED: "order:updated",
  ORDER_ACCEPTED: "order:accepted",
  ORDER_DELIVERED: "order:delivered",
  ORDER_COMPLETED: "order:completed",
  ORDER_CANCELLED: "order:cancelled",
  ORDER_DISPUTED: "order:disputed",
  TRANSACTION_CREATED: "transaction:created",
  TRANSACTION_REFUNDED: "transaction:refunded",
  REVIEW_SUBMITTED: "review:submitted",
  ITRADER_SUBMITTED: "itrader:submitted",
  DISPUTE_OPENED: "dispute:opened",
  DISPUTE_UPDATED: "dispute:updated",
  DISPUTE_RESOLVED: "dispute:resolved",
  TRUST_SCORE_UPDATED: "trust:score_updated",
  MEMBERSHIP_PURCHASED: "membership:purchased",
  MEMBERSHIP_RENEWED: "membership:renewed",
  MEMBERSHIP_EXPIRED: "membership:expired",
  MEMBERSHIP_UPGRADED: "membership:upgraded",
  MEMBERSHIP_CANCELLED: "membership:cancelled",
  MEMBERSHIP_ASSIGNED: "membership:assigned",
  MEMBERSHIP_REVOKED: "membership:revoked",
  PREMIUM_RESOURCE_ACCESSED: "premium_resource:accessed",
  LISTING_BOOST_PURCHASED: "listing_boost:purchased",
  ADMIN_SETTINGS_UPDATE: "admin:settings:update",
  ADMIN_DASHBOARD_VIEWED: "admin:dashboard:viewed",
  FEATURE_FLAG_CREATED: "admin:feature_flag:created",
  FEATURE_FLAG_TOGGLED: "admin:feature_flag:toggled",
  FEATURE_FLAG_DELETED: "admin:feature_flag:deleted",
  STAFF_ROLE_ASSIGNED: "admin:staff:role_assigned",
  USER_WARNED: "admin:user:warned",
  SYSTEM_ANNOUNCEMENT: "admin:announcement:created",
  ANNOUNCEMENT_UPDATED: "admin:announcement:updated",
  ANNOUNCEMENT_DELETED: "admin:announcement:deleted",
} as const;
