export enum RoleName {
  GUEST = "GUEST",
  MEMBER = "MEMBER",
  VIP = "VIP",
  SELLER = "SELLER",
  MODERATOR = "MODERATOR",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum Permission {
  // Forum permissions
  FORUM_READ = "forum:read",
  FORUM_CREATE = "forum:create",
  FORUM_UPDATE = "forum:update",
  FORUM_DELETE = "forum:delete",
  FORUM_MANAGE = "forum:manage",
  FORUM_STICKY = "forum:sticky",
  FORUM_LOCK = "forum:lock",
  FORUM_MOVE = "forum:move",
  VIEW_FORUM = "forum:view",
  VIEW_PREMIUM_FORUM = "forum:view_premium",
  MODERATE_FORUM = "forum:moderate",
  ADMIN_FORUM = "forum:admin",
  UPLOAD_ATTACHMENTS = "forum:upload_attachments",

  // Thread permissions
  THREAD_READ = "thread:read",
  THREAD_CREATE = "thread:create",
  THREAD_UPDATE = "thread:update",
  THREAD_DELETE = "thread:delete",
  THREAD_REPLY = "thread:reply",
  CREATE_THREAD = "thread:create_override",
  REPLY_THREAD = "thread:reply_override",
  EDIT_OWN_THREAD = "thread:edit_own",
  DELETE_OWN_THREAD = "thread:delete_own",
  VIEW_PREMIUM_THREAD = "thread:view_premium",
  PIN_THREAD = "thread:pin",
  LOCK_THREAD = "thread:lock",
  FEATURE_THREAD = "thread:feature",
  MODERATE_THREAD = "thread:moderate",

  // Post permissions
  POST_READ = "post:read",
  POST_CREATE = "post:create",
  POST_UPDATE = "post:update",
  POST_DELETE = "post:delete",
  POST_EDIT_OWN = "post:edit_own",
  POST_DELETE_OWN = "post:delete_own",
  POST_MODERATE = "post:moderate",
  POST_REPORT = "post:report",

  // User permissions
  USER_READ = "user:read",
  USER_UPDATE = "user:update",
  USER_DELETE = "user:delete",
  USER_BAN = "user:ban",
  USER_MANAGE = "user:manage",

  // Admin permissions
  ADMIN_ACCESS = "admin:access",
  ADMIN_MANAGE = "admin:manage",
  ADMIN_LOGS = "admin:logs",
  ADMIN_SETTINGS = "admin:settings",

  // Super Admin permissions
  SUPER_ADMIN_MANAGE = "super_admin:manage",
}

export type RoleHierarchy = {
  [key in RoleName]: number;
};

export const ROLE_HIERARCHY: RoleHierarchy = {
  [RoleName.GUEST]: 0,
  [RoleName.MEMBER]: 10,
  [RoleName.VIP]: 20,
  [RoleName.SELLER]: 30,
  [RoleName.MODERATOR]: 50,
  [RoleName.ADMIN]: 80,
  [RoleName.SUPER_ADMIN]: 100,
};

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  [RoleName.GUEST]: [
    Permission.FORUM_READ,
    Permission.THREAD_READ,
    Permission.VIEW_FORUM,
  ],
  [RoleName.MEMBER]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.VIP]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.SELLER]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.MODERATOR]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_DELETE,
    Permission.FORUM_MANAGE,
    Permission.FORUM_STICKY,
    Permission.FORUM_LOCK,
    Permission.FORUM_MOVE,
    Permission.VIEW_FORUM,
    Permission.MODERATE_FORUM,
    Permission.UPLOAD_ATTACHMENTS,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.THREAD_REPLY,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.PIN_THREAD,
    Permission.LOCK_THREAD,
    Permission.FEATURE_THREAD,
    Permission.MODERATE_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_MODERATE,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_BAN,
  ],
  [RoleName.ADMIN]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_DELETE,
    Permission.FORUM_MANAGE,
    Permission.FORUM_STICKY,
    Permission.FORUM_LOCK,
    Permission.FORUM_MOVE,
    Permission.VIEW_FORUM,
    Permission.VIEW_PREMIUM_FORUM,
    Permission.MODERATE_FORUM,
    Permission.ADMIN_FORUM,
    Permission.UPLOAD_ATTACHMENTS,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.THREAD_REPLY,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.VIEW_PREMIUM_THREAD,
    Permission.PIN_THREAD,
    Permission.LOCK_THREAD,
    Permission.FEATURE_THREAD,
    Permission.MODERATE_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_MODERATE,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_BAN,
    Permission.USER_MANAGE,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_MANAGE,
    Permission.ADMIN_LOGS,
    Permission.ADMIN_SETTINGS,
  ],
  [RoleName.SUPER_ADMIN]: Object.values(Permission),
};
