export enum RoleName {
  GUEST = "GUEST",
  MEMBER = "MEMBER",
  VIP = "VIP",
  SELLER = "SELLER",
  MODERATOR = "MODERATOR",
  SENIOR_MODERATOR = "SENIOR_MODERATOR",
  MARKETPLACE_MODERATOR = "MARKETPLACE_MODERATOR",
  SUPPORT_AGENT = "SUPPORT_AGENT",
  CONTENT_MANAGER = "CONTENT_MANAGER",
  ANALYST = "ANALYST",
  ADMIN = "ADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum Permission {
  // Forum permissions
  FORUM_READ = "forum:read",
  FORUM_CREATE = "forum:create",
  FORUM_UPDATE = "forum:update",
  FORUM_DELETE = "forum:delete",
  FORUM_MANAGE = "forum:manage",
  FORUM_STICKY = "forum:sticky",
  FORUM_LOCK = "forum:lock",
  FORUM_MOVE = "forum:move",
  VIEW_FORUM = "forum:view",
  VIEW_PREMIUM_FORUM = "forum:view_premium",
  MODERATE_FORUM = "forum:moderate",
  ADMIN_FORUM = "forum:admin",
  UPLOAD_ATTACHMENTS = "forum:upload_attachments",

  // Thread permissions
  THREAD_READ = "thread:read",
  THREAD_CREATE = "thread:create",
  THREAD_UPDATE = "thread:update",
  THREAD_DELETE = "thread:delete",
  THREAD_REPLY = "thread:reply",
  CREATE_THREAD = "thread:create_override",
  REPLY_THREAD = "thread:reply_override",
  EDIT_OWN_THREAD = "thread:edit_own",
  DELETE_OWN_THREAD = "thread:delete_own",
  VIEW_PREMIUM_THREAD = "thread:view_premium",
  PIN_THREAD = "thread:pin",
  LOCK_THREAD = "thread:lock",
  FEATURE_THREAD = "thread:feature",
  MODERATE_THREAD = "thread:moderate",

  // Post permissions
  POST_READ = "post:read",
  POST_CREATE = "post:create",
  POST_UPDATE = "post:update",
  POST_DELETE = "post:delete",
  POST_EDIT_OWN = "post:edit_own",
  POST_DELETE_OWN = "post:delete_own",
  POST_MODERATE = "post:moderate",
  POST_REPORT = "post:report",

  // User permissions
  USER_READ = "user:read",
  USER_UPDATE = "user:update",
  USER_DELETE = "user:delete",
  USER_BAN = "user:ban",
  USER_MANAGE = "user:manage",
  USER_WARN = "user:warn",
  USER_SUSPEND = "user:suspend",

  // Media permissions
  MEDIA_UPLOAD = "media:upload",
  MEDIA_DELETE = "media:delete",
  MEDIA_DELETE_OWN = "media:delete_own",
  MEDIA_MANAGE = "media:manage",
  ATTACHMENT_READ = "attachment:read",
  ATTACHMENT_UPLOAD = "attachment:upload",
  ATTACHMENT_DELETE = "attachment:delete",
  ATTACHMENT_DELETE_OWN = "attachment:delete_own",

  // Marketplace permissions
  MARKETPLACE_ACCESS = "marketplace:access",
  MARKETPLACE_MANAGE = "marketplace:manage",
  MARKETPLACE_MODERATE = "marketplace:moderate",
  MARKETPLACE_VERIFY_SELLERS = "marketplace:verify_sellers",
  MARKETPLACE_MANAGE_LISTINGS = "marketplace:manage_listings",
  MARKETPLACE_MANAGE_ORDERS = "marketplace:manage_orders",
  MARKETPLACE_MANAGE_DISPUTES = "marketplace:manage_disputes",
  MARKETPLACE_PROCESS_REFUNDS = "marketplace:process_refunds",

  // Membership permissions
  MEMBERSHIP_ACCESS = "membership:access",
  MEMBERSHIP_MANAGE = "membership:manage",
  MEMBERSHIP_GRANT = "membership:grant",
  MEMBERSHIP_REVOKE = "membership:revoke",
  MEMBERSHIP_MANAGE_PLANS = "membership:manage_plans",

  // Moderation permissions
  MODERATION_ACCESS = "moderation:access",
  MODERATION_MANAGE = "moderation:manage",
  MODERATION_MANAGE_REPORTS = "moderation:manage_reports",
  MODERATION_MANAGE_QUEUE = "moderation:manage_queue",
  MODERATION_BULK_ACTIONS = "moderation:bulk_actions",
  MODERATION_MANAGE_NOTES = "moderation:manage_notes",

  // Staff permissions
  STAFF_ACCESS = "staff:access",
  STAFF_MANAGE = "staff:manage",
  STAFF_MANAGE_ROLES = "staff:manage_roles",
  STAFF_MANAGE_PERMISSIONS = "staff:manage_permissions",
  STAFF_VIEW_LOGS = "staff:view_logs",

  // Analytics permissions
  ANALYTICS_ACCESS = "analytics:access",
  ANALYTICS_VIEW = "analytics:view",
  ANALYTICS_EXPORT = "analytics:export",
  ANALYTICS_VIEW_REVENUE = "analytics:view_revenue",
  ANALYTICS_VIEW_USERS = "analytics:view_users",

  // Admin permissions
  ADMIN_ACCESS = "admin:access",
  ADMIN_MANAGE = "admin:manage",
  ADMIN_LOGS = "admin:logs",
  ADMIN_SETTINGS = "admin:settings",
  ADMIN_VIEW_DASHBOARD = "admin:view_dashboard",
  ADMIN_MANAGE_SETTINGS = "admin:manage_settings",
  ADMIN_MANAGE_FEATURE_FLAGS = "admin:manage_feature_flags",
  ADMIN_MANAGE_ANNOUNCEMENTS = "admin:manage_announcements",
  ADMIN_MANAGE_SECURITY = "admin:manage_security",
  ADMIN_MANAGE_AUDIT = "admin:manage_audit",
  ADMIN_MANAGE_SUPPORT = "admin:manage_support",

  // Super Admin permissions
  SUPER_ADMIN_MANAGE = "super_admin:manage",
}

export type RoleHierarchy = {
  [key in RoleName]: number;
};

export const ROLE_HIERARCHY: RoleHierarchy = {
  [RoleName.GUEST]: 0,
  [RoleName.MEMBER]: 10,
  [RoleName.VIP]: 20,
  [RoleName.SELLER]: 30,
  [RoleName.SUPPORT_AGENT]: 35,
  [RoleName.CONTENT_MANAGER]: 40,
  [RoleName.ANALYST]: 45,
  [RoleName.MODERATOR]: 50,
  [RoleName.SENIOR_MODERATOR]: 60,
  [RoleName.MARKETPLACE_MODERATOR]: 65,
  [RoleName.ADMIN]: 80,
  [RoleName.SUPER_ADMIN]: 100,
};

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  [RoleName.GUEST]: [
    Permission.FORUM_READ,
    Permission.THREAD_READ,
    Permission.VIEW_FORUM,
  ],
  [RoleName.MEMBER]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE_OWN,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.VIP]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.VIEW_PREMIUM_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.VIEW_PREMIUM_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE_OWN,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.SELLER]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_REPLY,
    Permission.THREAD_UPDATE,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE_OWN,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
  ],
  [RoleName.SUPPORT_AGENT]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.POST_READ,
    Permission.POST_REPORT,
    Permission.USER_READ,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE_REPORTS,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.MARKETPLACE_ACCESS,
    Permission.MARKETPLACE_MANAGE_ORDERS,
  ],
  [RoleName.CONTENT_MANAGER]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_MANAGE,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_DELETE,
    Permission.POST_MODERATE,
    Permission.MEDIA_MANAGE,
    Permission.USER_READ,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE_QUEUE,
    Permission.MODERATION_BULK_ACTIONS,
    Permission.MODERATION_MANAGE_NOTES,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.ADMIN_MANAGE_ANNOUNCEMENTS,
  ],
  [RoleName.ANALYST]: [
    Permission.FORUM_READ,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.POST_READ,
    Permission.USER_READ,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.ANALYTICS_ACCESS,
    Permission.ANALYTICS_VIEW,
    Permission.ANALYTICS_EXPORT,
    Permission.ANALYTICS_VIEW_REVENUE,
    Permission.ANALYTICS_VIEW_USERS,
    Permission.MARKETPLACE_ACCESS,
    Permission.MEMBERSHIP_ACCESS,
  ],
  [RoleName.MODERATOR]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_DELETE,
    Permission.FORUM_MANAGE,
    Permission.FORUM_STICKY,
    Permission.FORUM_LOCK,
    Permission.FORUM_MOVE,
    Permission.VIEW_FORUM,
    Permission.MODERATE_FORUM,
    Permission.UPLOAD_ATTACHMENTS,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.THREAD_REPLY,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.PIN_THREAD,
    Permission.LOCK_THREAD,
    Permission.FEATURE_THREAD,
    Permission.MODERATE_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_MODERATE,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE,
    Permission.MEDIA_DELETE_OWN,
    Permission.MEDIA_MANAGE,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_BAN,
    Permission.USER_WARN,
    Permission.USER_SUSPEND,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE,
    Permission.MODERATION_MANAGE_REPORTS,
    Permission.MODERATION_MANAGE_QUEUE,
    Permission.MODERATION_MANAGE_NOTES,
    Permission.MARKETPLACE_ACCESS,
    Permission.MARKETPLACE_MODERATE,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
  ],
  [RoleName.SENIOR_MODERATOR]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_DELETE,
    Permission.FORUM_MANAGE,
    Permission.FORUM_STICKY,
    Permission.FORUM_LOCK,
    Permission.FORUM_MOVE,
    Permission.VIEW_FORUM,
    Permission.VIEW_PREMIUM_FORUM,
    Permission.MODERATE_FORUM,
    Permission.ADMIN_FORUM,
    Permission.UPLOAD_ATTACHMENTS,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.THREAD_REPLY,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.PIN_THREAD,
    Permission.LOCK_THREAD,
    Permission.FEATURE_THREAD,
    Permission.MODERATE_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_MODERATE,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE,
    Permission.MEDIA_DELETE_OWN,
    Permission.MEDIA_MANAGE,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_BAN,
    Permission.USER_WARN,
    Permission.USER_SUSPEND,
    Permission.USER_MANAGE,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE,
    Permission.MODERATION_MANAGE_REPORTS,
    Permission.MODERATION_MANAGE_QUEUE,
    Permission.MODERATION_BULK_ACTIONS,
    Permission.MODERATION_MANAGE_NOTES,
    Permission.MARKETPLACE_ACCESS,
    Permission.MARKETPLACE_MODERATE,
    Permission.MARKETPLACE_VERIFY_SELLERS,
    Permission.MARKETPLACE_MANAGE_LISTINGS,
    Permission.MARKETPLACE_MANAGE_ORDERS,
    Permission.MARKETPLACE_MANAGE_DISPUTES,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.ADMIN_LOGS,
    Permission.ADMIN_MANAGE_ANNOUNCEMENTS,
    Permission.STAFF_ACCESS,
    Permission.STAFF_VIEW_LOGS,
    Permission.ANALYTICS_ACCESS,
    Permission.ANALYTICS_VIEW,
  ],
  [RoleName.MARKETPLACE_MODERATOR]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.VIEW_FORUM,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_DELETE,
    Permission.POST_MODERATE,
    Permission.USER_READ,
    Permission.USER_BAN,
    Permission.MARKETPLACE_ACCESS,
    Permission.MARKETPLACE_MANAGE,
    Permission.MARKETPLACE_MODERATE,
    Permission.MARKETPLACE_VERIFY_SELLERS,
    Permission.MARKETPLACE_MANAGE_LISTINGS,
    Permission.MARKETPLACE_MANAGE_ORDERS,
    Permission.MARKETPLACE_MANAGE_DISPUTES,
    Permission.MARKETPLACE_PROCESS_REFUNDS,
    Permission.MEMBERSHIP_ACCESS,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE_REPORTS,
    Permission.MODERATION_MANAGE_NOTES,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.ADMIN_LOGS,
  ],
  [RoleName.ADMIN]: [
    Permission.FORUM_READ,
    Permission.FORUM_CREATE,
    Permission.FORUM_UPDATE,
    Permission.FORUM_DELETE,
    Permission.FORUM_MANAGE,
    Permission.FORUM_STICKY,
    Permission.FORUM_LOCK,
    Permission.FORUM_MOVE,
    Permission.VIEW_FORUM,
    Permission.VIEW_PREMIUM_FORUM,
    Permission.MODERATE_FORUM,
    Permission.ADMIN_FORUM,
    Permission.UPLOAD_ATTACHMENTS,
    Permission.THREAD_READ,
    Permission.THREAD_CREATE,
    Permission.THREAD_UPDATE,
    Permission.THREAD_DELETE,
    Permission.THREAD_REPLY,
    Permission.CREATE_THREAD,
    Permission.REPLY_THREAD,
    Permission.EDIT_OWN_THREAD,
    Permission.DELETE_OWN_THREAD,
    Permission.VIEW_PREMIUM_THREAD,
    Permission.PIN_THREAD,
    Permission.LOCK_THREAD,
    Permission.FEATURE_THREAD,
    Permission.MODERATE_THREAD,
    Permission.POST_READ,
    Permission.POST_CREATE,
    Permission.POST_UPDATE,
    Permission.POST_DELETE,
    Permission.POST_EDIT_OWN,
    Permission.POST_DELETE_OWN,
    Permission.POST_MODERATE,
    Permission.POST_REPORT,
    Permission.MEDIA_UPLOAD,
    Permission.MEDIA_DELETE,
    Permission.MEDIA_DELETE_OWN,
    Permission.MEDIA_MANAGE,
    Permission.ATTACHMENT_READ,
    Permission.ATTACHMENT_UPLOAD,
    Permission.ATTACHMENT_DELETE,
    Permission.ATTACHMENT_DELETE_OWN,
    Permission.USER_READ,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_BAN,
    Permission.USER_MANAGE,
    Permission.USER_WARN,
    Permission.USER_SUSPEND,
    Permission.MARKETPLACE_ACCESS,
    Permission.MARKETPLACE_MANAGE,
    Permission.MARKETPLACE_MODERATE,
    Permission.MARKETPLACE_VERIFY_SELLERS,
    Permission.MARKETPLACE_MANAGE_LISTINGS,
    Permission.MARKETPLACE_MANAGE_ORDERS,
    Permission.MARKETPLACE_MANAGE_DISPUTES,
    Permission.MARKETPLACE_PROCESS_REFUNDS,
    Permission.MEMBERSHIP_ACCESS,
    Permission.MEMBERSHIP_MANAGE,
    Permission.MEMBERSHIP_GRANT,
    Permission.MEMBERSHIP_REVOKE,
    Permission.MEMBERSHIP_MANAGE_PLANS,
    Permission.MODERATION_ACCESS,
    Permission.MODERATION_MANAGE,
    Permission.MODERATION_MANAGE_REPORTS,
    Permission.MODERATION_MANAGE_QUEUE,
    Permission.MODERATION_BULK_ACTIONS,
    Permission.MODERATION_MANAGE_NOTES,
    Permission.STAFF_ACCESS,
    Permission.STAFF_MANAGE,
    Permission.STAFF_MANAGE_ROLES,
    Permission.STAFF_VIEW_LOGS,
    Permission.ANALYTICS_ACCESS,
    Permission.ANALYTICS_VIEW,
    Permission.ANALYTICS_EXPORT,
    Permission.ANALYTICS_VIEW_REVENUE,
    Permission.ANALYTICS_VIEW_USERS,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_MANAGE,
    Permission.ADMIN_LOGS,
    Permission.ADMIN_SETTINGS,
    Permission.ADMIN_VIEW_DASHBOARD,
    Permission.ADMIN_MANAGE_SETTINGS,
    Permission.ADMIN_MANAGE_FEATURE_FLAGS,
    Permission.ADMIN_MANAGE_ANNOUNCEMENTS,
    Permission.ADMIN_MANAGE_SECURITY,
    Permission.ADMIN_MANAGE_AUDIT,
    Permission.ADMIN_MANAGE_SUPPORT,
  ],
  [RoleName.SUPER_ADMIN]: Object.values(Permission),
};
